### ISSUE TITLE
Spotify API key is visible

### ISSUE THREAD

**Issue by jyap808** [cgzirim/not-shazam#7]
Here:
https://github.com/cgzirim/not-shazam/blob/main/spotify/youtube.go#L21

**Comment by scripturial** [comment]
Someone told everyone on hacker news that your key is in that file.

**Comment by cgzirim** [comment]
Thanks for bringing this to my attention. It has been invalidated and removed.

**Comment by cgzirim** [comment]
@jyap808 
Thanks for bringing this to my attention. API key has been invalidated and removed.
