### ISSUE TITLE
Large files in history

### ISSUE THREAD

**Issue by FrankSansC** [cgzirim/not-shazam#8]
In your initial commit 13af8add1d0a0e998e747e4c013603fda83eb0b7 you have added several "large files". Beyond the legal aspect of those "large files", and even though you've deleted them in commit 7fc2b60d8dd4f715e1019c9501b3b8f25094c979, they are still in git history. There's also a 10MB `output.ivf` file deleted in commit b1b327271b672700ef0fbe5c059c04c382fc68cb. All of this makes this repository quite large to clone (146MB).

You should try to cleanup your git history to save some space.

**Comment by cgzirim** [comment]
Large files (output.ivf, songs, songsss) have been removed from the project's history.
